const TravelochainConstants = {
  ADD_A_CITY: 'Add City',
  ADMIN_LVL_1: 'administrative_area_level_1',
  APP: 'App',
  APP_TITLE: 'App-title',
  AVAILABLE_SOON: 'Available soon...',
  AVERAGE: 2,
  CANCEL: 'Cancel',
  CENTER: 'center',
  COUNTRY: 'country',
  DATE_STRING: ' 12:00:00 +0000',
  END_DATE: 'End Date',
  FLEX: 'flex',
  GAS_FEE_MESSAGE: 'Doing so will incur a small gas fee.',
  LANDSCAPE: 'landscape',
  LIST_VIEW: 'List View',
  LOADING_MAP: 'loading map...',
  LOCAL_PROVIDER: 'http://127.0.0.1:9545',
  LOCAL_PROVIDER_MSG: 'No web3 instance injected, using Local web3.',
  LOCALITY: 'locality',
  MAP: 'Map',
  MAP_HEIGHT: '85vh',
  MAP_LAT: 40,
  MAP_LNG: -75,
  MAP_TYPE_ID: 'roadmap',
  MAP_VIEW: 'Map View',
  MAP_WIDTH: '85vw',
  MAP_ZOOM: 2,
  NAME: 'travelochain',
  NOTES_HINT_TEXT: 'Special Memories, Experiences, Etc',
  NOTES_LABEL_TEXT: 'Notes about your trip to ',
  POWERED_BY_GOOGLE: './images/powered_by_google_default.png',
  SAVE: 'Save',
  SAVE_DIALOG_MESSAGE: 'Are you sure you want to save this forever?',
  SEARCH: 'Search',
  SEARCH_OPTIONS: {
    types: ['(cities)'],
  },
  START_DATE: 'Start Date',
  STATS_VIEW: 'Stats View',
  STRING_SPACE: ' ',
  TOOLBAR_MAP_VIEW: 1,
  TRIP: ' Trip',
  TRIP_INFORMATION: ' Trip Information',
  UNDEFINED: 'undefined',
  USING_WEB3: 'Using web3 detected from external source',
  WEB3_ERROR: 'Error finding web3.',
  WHITE: 'white',
  X: 'x',
};

module.exports = TravelochainConstants;